version: '3'
services:
  iotdb:
    image: linuxserver/mariadb:latest
    container_name: iotdb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: very-secret-word
    volumes:
      - ./data/db-pi:/config

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
